// Country data with flags, capitals, and regions
export interface Country {
  name: string
  code: string
  capital: string
  region: string
  subregion: string
  flag: string
  latlng: [number, number]
  difficulty: "easy" | "medium" | "hard"
}

// Comprehensive country data
export const countries: Country[] = [
  // EASY - Well-known countries (30)
  {
    name: "United States",
    code: "US",
    capital: "Washington, D.C.",
    region: "Americas",
    subregion: "Northern America",
    flag: "🇺🇸",
    latlng: [38, -97],
    difficulty: "easy",
  },
  {
    name: "United Kingdom",
    code: "GB",
    capital: "London",
    region: "Europe",
    subregion: "Northern Europe",
    flag: "🇬🇧",
    latlng: [54, -2],
    difficulty: "easy",
  },
  {
    name: "France",
    code: "FR",
    capital: "Paris",
    region: "Europe",
    subregion: "Western Europe",
    flag: "🇫🇷",
    latlng: [46, 2],
    difficulty: "easy",
  },
  {
    name: "Germany",
    code: "DE",
    capital: "Berlin",
    region: "Europe",
    subregion: "Western Europe",
    flag: "🇩🇪",
    latlng: [51, 9],
    difficulty: "easy",
  },
  {
    name: "Italy",
    code: "IT",
    capital: "Rome",
    region: "Europe",
    subregion: "Southern Europe",
    flag: "🇮🇹",
    latlng: [42.8333, 12.8333],
    difficulty: "easy",
  },
  {
    name: "Spain",
    code: "ES",
    capital: "Madrid",
    region: "Europe",
    subregion: "Southern Europe",
    flag: "🇪🇸",
    latlng: [40, -4],
    difficulty: "easy",
  },
  {
    name: "Canada",
    code: "CA",
    capital: "Ottawa",
    region: "Americas",
    subregion: "Northern America",
    flag: "🇨🇦",
    latlng: [60, -95],
    difficulty: "easy",
  },
  {
    name: "Australia",
    code: "AU",
    capital: "Canberra",
    region: "Oceania",
    subregion: "Australia and New Zealand",
    flag: "🇦🇺",
    latlng: [-27, 133],
    difficulty: "easy",
  },
  {
    name: "Japan",
    code: "JP",
    capital: "Tokyo",
    region: "Asia",
    subregion: "Eastern Asia",
    flag: "🇯🇵",
    latlng: [36, 138],
    difficulty: "easy",
  },
  {
    name: "China",
    code: "CN",
    capital: "Beijing",
    region: "Asia",
    subregion: "Eastern Asia",
    flag: "🇨🇳",
    latlng: [35, 105],
    difficulty: "easy",
  },
  {
    name: "India",
    code: "IN",
    capital: "New Delhi",
    region: "Asia",
    subregion: "Southern Asia",
    flag: "🇮🇳",
    latlng: [20, 77],
    difficulty: "easy",
  },
  {
    name: "Brazil",
    code: "BR",
    capital: "Brasília",
    region: "Americas",
    subregion: "South America",
    flag: "🇧🇷",
    latlng: [-10, -55],
    difficulty: "easy",
  },
  {
    name: "Mexico",
    code: "MX",
    capital: "Mexico City",
    region: "Americas",
    subregion: "Central America",
    flag: "🇲🇽",
    latlng: [23, -102],
    difficulty: "easy",
  },
  {
    name: "Russia",
    code: "RU",
    capital: "Moscow",
    region: "Europe",
    subregion: "Eastern Europe",
    flag: "🇷🇺",
    latlng: [60, 100],
    difficulty: "easy",
  },
  {
    name: "South Korea",
    code: "KR",
    capital: "Seoul",
    region: "Asia",
    subregion: "Eastern Asia",
    flag: "🇰🇷",
    latlng: [37, 127.5],
    difficulty: "easy",
  },
  {
    name: "Netherlands",
    code: "NL",
    capital: "Amsterdam",
    region: "Europe",
    subregion: "Western Europe",
    flag: "🇳🇱",
    latlng: [52.5, 5.75],
    difficulty: "easy",
  },
  {
    name: "Switzerland",
    code: "CH",
    capital: "Bern",
    region: "Europe",
    subregion: "Western Europe",
    flag: "🇨🇭",
    latlng: [47, 8],
    difficulty: "easy",
  },
  {
    name: "Sweden",
    code: "SE",
    capital: "Stockholm",
    region: "Europe",
    subregion: "Northern Europe",
    flag: "🇸🇪",
    latlng: [62, 15],
    difficulty: "easy",
  },
  {
    name: "Norway",
    code: "NO",
    capital: "Oslo",
    region: "Europe",
    subregion: "Northern Europe",
    flag: "🇳🇴",
    latlng: [62, 10],
    difficulty: "easy",
  },
  {
    name: "Argentina",
    code: "AR",
    capital: "Buenos Aires",
    region: "Americas",
    subregion: "South America",
    flag: "🇦🇷",
    latlng: [-34, -64],
    difficulty: "easy",
  },
  {
    name: "South Africa",
    code: "ZA",
    capital: "Pretoria",
    region: "Africa",
    subregion: "Southern Africa",
    flag: "🇿🇦",
    latlng: [-29, 24],
    difficulty: "easy",
  },
  {
    name: "Egypt",
    code: "EG",
    capital: "Cairo",
    region: "Africa",
    subregion: "Northern Africa",
    flag: "🇪🇬",
    latlng: [27, 30],
    difficulty: "easy",
  },
  {
    name: "Turkey",
    code: "TR",
    capital: "Ankara",
    region: "Asia",
    subregion: "Western Asia",
    flag: "🇹🇷",
    latlng: [39, 35],
    difficulty: "easy",
  },
  {
    name: "Greece",
    code: "GR",
    capital: "Athens",
    region: "Europe",
    subregion: "Southern Europe",
    flag: "🇬🇷",
    latlng: [39, 22],
    difficulty: "easy",
  },
  {
    name: "Portugal",
    code: "PT",
    capital: "Lisbon",
    region: "Europe",
    subregion: "Southern Europe",
    flag: "🇵🇹",
    latlng: [39.5, -8],
    difficulty: "easy",
  },
  {
    name: "Poland",
    code: "PL",
    capital: "Warsaw",
    region: "Europe",
    subregion: "Central Europe",
    flag: "🇵🇱",
    latlng: [52, 20],
    difficulty: "easy",
  },
  {
    name: "Ireland",
    code: "IE",
    capital: "Dublin",
    region: "Europe",
    subregion: "Northern Europe",
    flag: "🇮🇪",
    latlng: [53, -8],
    difficulty: "easy",
  },
  {
    name: "New Zealand",
    code: "NZ",
    capital: "Wellington",
    region: "Oceania",
    subregion: "Australia and New Zealand",
    flag: "🇳🇿",
    latlng: [-41, 174],
    difficulty: "easy",
  },
  {
    name: "Thailand",
    code: "TH",
    capital: "Bangkok",
    region: "Asia",
    subregion: "South-Eastern Asia",
    flag: "🇹🇭",
    latlng: [15, 100],
    difficulty: "easy",
  },
  {
    name: "Indonesia",
    code: "ID",
    capital: "Jakarta",
    region: "Asia",
    subregion: "South-Eastern Asia",
    flag: "🇮🇩",
    latlng: [-5, 120],
    difficulty: "easy",
  },

  // MEDIUM - Less commonly known (70 more)
  {
    name: "Austria",
    code: "AT",
    capital: "Vienna",
    region: "Europe",
    subregion: "Western Europe",
    flag: "🇦🇹",
    latlng: [47.3333, 13.3333],
    difficulty: "medium",
  },
  {
    name: "Belgium",
    code: "BE",
    capital: "Brussels",
    region: "Europe",
    subregion: "Western Europe",
    flag: "🇧🇪",
    latlng: [50.8333, 4],
    difficulty: "medium",
  },
  {
    name: "Denmark",
    code: "DK",
    capital: "Copenhagen",
    region: "Europe",
    subregion: "Northern Europe",
    flag: "🇩🇰",
    latlng: [56, 10],
    difficulty: "medium",
  },
  {
    name: "Finland",
    code: "FI",
    capital: "Helsinki",
    region: "Europe",
    subregion: "Northern Europe",
    flag: "🇫🇮",
    latlng: [64, 26],
    difficulty: "medium",
  },
  {
    name: "Czech Republic",
    code: "CZ",
    capital: "Prague",
    region: "Europe",
    subregion: "Central Europe",
    flag: "🇨🇿",
    latlng: [49.75, 15.5],
    difficulty: "medium",
  },
  {
    name: "Hungary",
    code: "HU",
    capital: "Budapest",
    region: "Europe",
    subregion: "Central Europe",
    flag: "🇭🇺",
    latlng: [47, 20],
    difficulty: "medium",
  },
  {
    name: "Romania",
    code: "RO",
    capital: "Bucharest",
    region: "Europe",
    subregion: "Eastern Europe",
    flag: "🇷🇴",
    latlng: [46, 25],
    difficulty: "medium",
  },
  {
    name: "Ukraine",
    code: "UA",
    capital: "Kyiv",
    region: "Europe",
    subregion: "Eastern Europe",
    flag: "🇺🇦",
    latlng: [49, 32],
    difficulty: "medium",
  },
  {
    name: "Vietnam",
    code: "VN",
    capital: "Hanoi",
    region: "Asia",
    subregion: "South-Eastern Asia",
    flag: "🇻🇳",
    latlng: [16.1667, 107.8333],
    difficulty: "medium",
  },
  {
    name: "Philippines",
    code: "PH",
    capital: "Manila",
    region: "Asia",
    subregion: "South-Eastern Asia",
    flag: "🇵🇭",
    latlng: [13, 122],
    difficulty: "medium",
  },
  {
    name: "Malaysia",
    code: "MY",
    capital: "Kuala Lumpur",
    region: "Asia",
    subregion: "South-Eastern Asia",
    flag: "🇲🇾",
    latlng: [2.5, 112.5],
    difficulty: "medium",
  },
  {
    name: "Singapore",
    code: "SG",
    capital: "Singapore",
    region: "Asia",
    subregion: "South-Eastern Asia",
    flag: "🇸🇬",
    latlng: [1.3667, 103.8],
    difficulty: "medium",
  },
  {
    name: "Pakistan",
    code: "PK",
    capital: "Islamabad",
    region: "Asia",
    subregion: "Southern Asia",
    flag: "🇵🇰",
    latlng: [30, 70],
    difficulty: "medium",
  },
  {
    name: "Bangladesh",
    code: "BD",
    capital: "Dhaka",
    region: "Asia",
    subregion: "Southern Asia",
    flag: "🇧🇩",
    latlng: [24, 90],
    difficulty: "medium",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    capital: "Sri Jayawardenepura Kotte",
    region: "Asia",
    subregion: "Southern Asia",
    flag: "🇱🇰",
    latlng: [7, 81],
    difficulty: "medium",
  },
  {
    name: "Nepal",
    code: "NP",
    capital: "Kathmandu",
    region: "Asia",
    subregion: "Southern Asia",
    flag: "🇳🇵",
    latlng: [28, 84],
    difficulty: "medium",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    capital: "Riyadh",
    region: "Asia",
    subregion: "Western Asia",
    flag: "🇸🇦",
    latlng: [25, 45],
    difficulty: "medium",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    capital: "Abu Dhabi",
    region: "Asia",
    subregion: "Western Asia",
    flag: "🇦🇪",
    latlng: [24, 54],
    difficulty: "medium",
  },
  {
    name: "Israel",
    code: "IL",
    capital: "Jerusalem",
    region: "Asia",
    subregion: "Western Asia",
    flag: "🇮🇱",
    latlng: [31.47, 35.13],
    difficulty: "medium",
  },
  {
    name: "Iran",
    code: "IR",
    capital: "Tehran",
    region: "Asia",
    subregion: "Southern Asia",
    flag: "🇮🇷",
    latlng: [32, 53],
    difficulty: "medium",
  },
  {
    name: "Iraq",
    code: "IQ",
    capital: "Baghdad",
    region: "Asia",
    subregion: "Western Asia",
    flag: "🇮🇶",
    latlng: [33, 44],
    difficulty: "medium",
  },
  {
    name: "Nigeria",
    code: "NG",
    capital: "Abuja",
    region: "Africa",
    subregion: "Western Africa",
    flag: "🇳🇬",
    latlng: [10, 8],
    difficulty: "medium",
  },
  {
    name: "Kenya",
    code: "KE",
    capital: "Nairobi",
    region: "Africa",
    subregion: "Eastern Africa",
    flag: "🇰🇪",
    latlng: [1, 38],
    difficulty: "medium",
  },
  {
    name: "Morocco",
    code: "MA",
    capital: "Rabat",
    region: "Africa",
    subregion: "Northern Africa",
    flag: "🇲🇦",
    latlng: [32, -5],
    difficulty: "medium",
  },
  {
    name: "Ghana",
    code: "GH",
    capital: "Accra",
    region: "Africa",
    subregion: "Western Africa",
    flag: "🇬🇭",
    latlng: [8, -2],
    difficulty: "medium",
  },
  {
    name: "Ethiopia",
    code: "ET",
    capital: "Addis Ababa",
    region: "Africa",
    subregion: "Eastern Africa",
    flag: "🇪🇹",
    latlng: [8, 38],
    difficulty: "medium",
  },
  {
    name: "Colombia",
    code: "CO",
    capital: "Bogotá",
    region: "Americas",
    subregion: "South America",
    flag: "🇨🇴",
    latlng: [4, -72],
    difficulty: "medium",
  },
  {
    name: "Peru",
    code: "PE",
    capital: "Lima",
    region: "Americas",
    subregion: "South America",
    flag: "🇵🇪",
    latlng: [-10, -76],
    difficulty: "medium",
  },
  {
    name: "Chile",
    code: "CL",
    capital: "Santiago",
    region: "Americas",
    subregion: "South America",
    flag: "🇨🇱",
    latlng: [-30, -71],
    difficulty: "medium",
  },
  {
    name: "Venezuela",
    code: "VE",
    capital: "Caracas",
    region: "Americas",
    subregion: "South America",
    flag: "🇻🇪",
    latlng: [8, -66],
    difficulty: "medium",
  },
  {
    name: "Cuba",
    code: "CU",
    capital: "Havana",
    region: "Americas",
    subregion: "Caribbean",
    flag: "🇨🇺",
    latlng: [21.5, -80],
    difficulty: "medium",
  },
  {
    name: "Jamaica",
    code: "JM",
    capital: "Kingston",
    region: "Americas",
    subregion: "Caribbean",
    flag: "🇯🇲",
    latlng: [18.25, -77.5],
    difficulty: "medium",
  },
  {
    name: "Croatia",
    code: "HR",
    capital: "Zagreb",
    region: "Europe",
    subregion: "Southern Europe",
    flag: "🇭🇷",
    latlng: [45.1667, 15.5],
    difficulty: "medium",
  },
  {
    name: "Serbia",
    code: "RS",
    capital: "Belgrade",
    region: "Europe",
    subregion: "Southern Europe",
    flag: "🇷🇸",
    latlng: [44, 21],
    difficulty: "medium",
  },
  {
    name: "Bulgaria",
    code: "BG",
    capital: "Sofia",
    region: "Europe",
    subregion: "Eastern Europe",
    flag: "🇧🇬",
    latlng: [43, 25],
    difficulty: "medium",
  },
  {
    name: "Slovakia",
    code: "SK",
    capital: "Bratislava",
    region: "Europe",
    subregion: "Central Europe",
    flag: "🇸🇰",
    latlng: [48.6667, 19.5],
    difficulty: "medium",
  },
  {
    name: "Slovenia",
    code: "SI",
    capital: "Ljubljana",
    region: "Europe",
    subregion: "Southern Europe",
    flag: "🇸🇮",
    latlng: [46.1167, 14.8167],
    difficulty: "medium",
  },
  {
    name: "Lithuania",
    code: "LT",
    capital: "Vilnius",
    region: "Europe",
    subregion: "Northern Europe",
    flag: "🇱🇹",
    latlng: [56, 24],
    difficulty: "medium",
  },
  {
    name: "Latvia",
    code: "LV",
    capital: "Riga",
    region: "Europe",
    subregion: "Northern Europe",
    flag: "🇱🇻",
    latlng: [57, 25],
    difficulty: "medium",
  },
  {
    name: "Estonia",
    code: "EE",
    capital: "Tallinn",
    region: "Europe",
    subregion: "Northern Europe",
    flag: "🇪🇪",
    latlng: [59, 26],
    difficulty: "medium",
  },
  {
    name: "Iceland",
    code: "IS",
    capital: "Reykjavik",
    region: "Europe",
    subregion: "Northern Europe",
    flag: "🇮🇸",
    latlng: [65, -18],
    difficulty: "medium",
  },
  {
    name: "Luxembourg",
    code: "LU",
    capital: "Luxembourg",
    region: "Europe",
    subregion: "Western Europe",
    flag: "🇱🇺",
    latlng: [49.75, 6.1667],
    difficulty: "medium",
  },
  {
    name: "Malta",
    code: "MT",
    capital: "Valletta",
    region: "Europe",
    subregion: "Southern Europe",
    flag: "🇲🇹",
    latlng: [35.8333, 14.5833],
    difficulty: "medium",
  },
  {
    name: "Cyprus",
    code: "CY",
    capital: "Nicosia",
    region: "Europe",
    subregion: "Eastern Europe",
    flag: "🇨🇾",
    latlng: [35, 33],
    difficulty: "medium",
  },
  {
    name: "Panama",
    code: "PA",
    capital: "Panama City",
    region: "Americas",
    subregion: "Central America",
    flag: "🇵🇦",
    latlng: [9, -80],
    difficulty: "medium",
  },
  {
    name: "Costa Rica",
    code: "CR",
    capital: "San José",
    region: "Americas",
    subregion: "Central America",
    flag: "🇨🇷",
    latlng: [10, -84],
    difficulty: "medium",
  },
  {
    name: "Ecuador",
    code: "EC",
    capital: "Quito",
    region: "Americas",
    subregion: "South America",
    flag: "🇪🇨",
    latlng: [-2, -77.5],
    difficulty: "medium",
  },
  {
    name: "Uruguay",
    code: "UY",
    capital: "Montevideo",
    region: "Americas",
    subregion: "South America",
    flag: "🇺🇾",
    latlng: [-33, -56],
    difficulty: "medium",
  },
  {
    name: "Paraguay",
    code: "PY",
    capital: "Asunción",
    region: "Americas",
    subregion: "South America",
    flag: "🇵🇾",
    latlng: [-23, -58],
    difficulty: "medium",
  },
  {
    name: "Bolivia",
    code: "BO",
    capital: "Sucre",
    region: "Americas",
    subregion: "South America",
    flag: "🇧🇴",
    latlng: [-17, -65],
    difficulty: "medium",
  },

  // HARD - Obscure countries (50 more)
  {
    name: "Bhutan",
    code: "BT",
    capital: "Thimphu",
    region: "Asia",
    subregion: "Southern Asia",
    flag: "🇧🇹",
    latlng: [27.5, 90.5],
    difficulty: "hard",
  },
  {
    name: "Brunei",
    code: "BN",
    capital: "Bandar Seri Begawan",
    region: "Asia",
    subregion: "South-Eastern Asia",
    flag: "🇧🇳",
    latlng: [4.5, 114.6667],
    difficulty: "hard",
  },
  {
    name: "Cambodia",
    code: "KH",
    capital: "Phnom Penh",
    region: "Asia",
    subregion: "South-Eastern Asia",
    flag: "🇰🇭",
    latlng: [13, 105],
    difficulty: "hard",
  },
  {
    name: "Laos",
    code: "LA",
    capital: "Vientiane",
    region: "Asia",
    subregion: "South-Eastern Asia",
    flag: "🇱🇦",
    latlng: [18, 105],
    difficulty: "hard",
  },
  {
    name: "Myanmar",
    code: "MM",
    capital: "Naypyidaw",
    region: "Asia",
    subregion: "South-Eastern Asia",
    flag: "🇲🇲",
    latlng: [22, 98],
    difficulty: "hard",
  },
  {
    name: "Mongolia",
    code: "MN",
    capital: "Ulaanbaatar",
    region: "Asia",
    subregion: "Eastern Asia",
    flag: "🇲🇳",
    latlng: [46, 105],
    difficulty: "hard",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    capital: "Astana",
    region: "Asia",
    subregion: "Central Asia",
    flag: "🇰🇿",
    latlng: [48, 68],
    difficulty: "hard",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    capital: "Tashkent",
    region: "Asia",
    subregion: "Central Asia",
    flag: "🇺🇿",
    latlng: [41, 64],
    difficulty: "hard",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    capital: "Ashgabat",
    region: "Asia",
    subregion: "Central Asia",
    flag: "🇹🇲",
    latlng: [40, 60],
    difficulty: "hard",
  },
  {
    name: "Tajikistan",
    code: "TJ",
    capital: "Dushanbe",
    region: "Asia",
    subregion: "Central Asia",
    flag: "🇹🇯",
    latlng: [39, 71],
    difficulty: "hard",
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    capital: "Bishkek",
    region: "Asia",
    subregion: "Central Asia",
    flag: "🇰🇬",
    latlng: [41, 75],
    difficulty: "hard",
  },
  {
    name: "Afghanistan",
    code: "AF",
    capital: "Kabul",
    region: "Asia",
    subregion: "Southern Asia",
    flag: "🇦🇫",
    latlng: [33, 65],
    difficulty: "hard",
  },
  {
    name: "Yemen",
    code: "YE",
    capital: "Sana'a",
    region: "Asia",
    subregion: "Western Asia",
    flag: "🇾🇪",
    latlng: [15, 48],
    difficulty: "hard",
  },
  {
    name: "Oman",
    code: "OM",
    capital: "Muscat",
    region: "Asia",
    subregion: "Western Asia",
    flag: "🇴🇲",
    latlng: [21, 57],
    difficulty: "hard",
  },
  {
    name: "Kuwait",
    code: "KW",
    capital: "Kuwait City",
    region: "Asia",
    subregion: "Western Asia",
    flag: "🇰🇼",
    latlng: [29.5, 45.75],
    difficulty: "hard",
  },
  {
    name: "Qatar",
    code: "QA",
    capital: "Doha",
    region: "Asia",
    subregion: "Western Asia",
    flag: "🇶🇦",
    latlng: [25.5, 51.25],
    difficulty: "hard",
  },
  {
    name: "Bahrain",
    code: "BH",
    capital: "Manama",
    region: "Asia",
    subregion: "Western Asia",
    flag: "🇧🇭",
    latlng: [26, 50.55],
    difficulty: "hard",
  },
  {
    name: "Jordan",
    code: "JO",
    capital: "Amman",
    region: "Asia",
    subregion: "Western Asia",
    flag: "🇯🇴",
    latlng: [31, 36],
    difficulty: "hard",
  },
  {
    name: "Lebanon",
    code: "LB",
    capital: "Beirut",
    region: "Asia",
    subregion: "Western Asia",
    flag: "🇱🇧",
    latlng: [33.8333, 35.8333],
    difficulty: "hard",
  },
  {
    name: "Syria",
    code: "SY",
    capital: "Damascus",
    region: "Asia",
    subregion: "Western Asia",
    flag: "🇸🇾",
    latlng: [35, 38],
    difficulty: "hard",
  },
  {
    name: "Georgia",
    code: "GE",
    capital: "Tbilisi",
    region: "Asia",
    subregion: "Western Asia",
    flag: "🇬🇪",
    latlng: [42, 43.5],
    difficulty: "hard",
  },
  {
    name: "Armenia",
    code: "AM",
    capital: "Yerevan",
    region: "Asia",
    subregion: "Western Asia",
    flag: "🇦🇲",
    latlng: [40, 45],
    difficulty: "hard",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    capital: "Baku",
    region: "Asia",
    subregion: "Western Asia",
    flag: "🇦🇿",
    latlng: [40.5, 47.5],
    difficulty: "hard",
  },
  {
    name: "Tanzania",
    code: "TZ",
    capital: "Dodoma",
    region: "Africa",
    subregion: "Eastern Africa",
    flag: "🇹🇿",
    latlng: [-6, 35],
    difficulty: "hard",
  },
  {
    name: "Uganda",
    code: "UG",
    capital: "Kampala",
    region: "Africa",
    subregion: "Eastern Africa",
    flag: "🇺🇬",
    latlng: [1, 32],
    difficulty: "hard",
  },
  {
    name: "Rwanda",
    code: "RW",
    capital: "Kigali",
    region: "Africa",
    subregion: "Eastern Africa",
    flag: "🇷🇼",
    latlng: [-2, 30],
    difficulty: "hard",
  },
  {
    name: "Zambia",
    code: "ZM",
    capital: "Lusaka",
    region: "Africa",
    subregion: "Eastern Africa",
    flag: "🇿🇲",
    latlng: [-15, 30],
    difficulty: "hard",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    capital: "Harare",
    region: "Africa",
    subregion: "Eastern Africa",
    flag: "🇿🇼",
    latlng: [-20, 30],
    difficulty: "hard",
  },
  {
    name: "Botswana",
    code: "BW",
    capital: "Gaborone",
    region: "Africa",
    subregion: "Southern Africa",
    flag: "🇧🇼",
    latlng: [-22, 24],
    difficulty: "hard",
  },
  {
    name: "Namibia",
    code: "NA",
    capital: "Windhoek",
    region: "Africa",
    subregion: "Southern Africa",
    flag: "🇳🇦",
    latlng: [-22, 17],
    difficulty: "hard",
  },
  {
    name: "Mozambique",
    code: "MZ",
    capital: "Maputo",
    region: "Africa",
    subregion: "Eastern Africa",
    flag: "🇲🇿",
    latlng: [-18.25, 35],
    difficulty: "hard",
  },
  {
    name: "Madagascar",
    code: "MG",
    capital: "Antananarivo",
    region: "Africa",
    subregion: "Eastern Africa",
    flag: "🇲🇬",
    latlng: [-20, 47],
    difficulty: "hard",
  },
  {
    name: "Senegal",
    code: "SN",
    capital: "Dakar",
    region: "Africa",
    subregion: "Western Africa",
    flag: "🇸🇳",
    latlng: [14, -14],
    difficulty: "hard",
  },
  {
    name: "Ivory Coast",
    code: "CI",
    capital: "Yamoussoukro",
    region: "Africa",
    subregion: "Western Africa",
    flag: "🇨🇮",
    latlng: [8, -5],
    difficulty: "hard",
  },
  {
    name: "Cameroon",
    code: "CM",
    capital: "Yaoundé",
    region: "Africa",
    subregion: "Middle Africa",
    flag: "🇨🇲",
    latlng: [6, 12],
    difficulty: "hard",
  },
  {
    name: "Angola",
    code: "AO",
    capital: "Luanda",
    region: "Africa",
    subregion: "Middle Africa",
    flag: "🇦🇴",
    latlng: [-12.5, 18.5],
    difficulty: "hard",
  },
  {
    name: "Democratic Republic of the Congo",
    code: "CD",
    capital: "Kinshasa",
    region: "Africa",
    subregion: "Middle Africa",
    flag: "🇨🇩",
    latlng: [0, 25],
    difficulty: "hard",
  },
  {
    name: "Algeria",
    code: "DZ",
    capital: "Algiers",
    region: "Africa",
    subregion: "Northern Africa",
    flag: "🇩🇿",
    latlng: [28, 3],
    difficulty: "hard",
  },
  {
    name: "Tunisia",
    code: "TN",
    capital: "Tunis",
    region: "Africa",
    subregion: "Northern Africa",
    flag: "🇹🇳",
    latlng: [34, 9],
    difficulty: "hard",
  },
  {
    name: "Libya",
    code: "LY",
    capital: "Tripoli",
    region: "Africa",
    subregion: "Northern Africa",
    flag: "🇱🇾",
    latlng: [25, 17],
    difficulty: "hard",
  },
  {
    name: "Sudan",
    code: "SD",
    capital: "Khartoum",
    region: "Africa",
    subregion: "Northern Africa",
    flag: "🇸🇩",
    latlng: [15, 30],
    difficulty: "hard",
  },
  {
    name: "Honduras",
    code: "HN",
    capital: "Tegucigalpa",
    region: "Americas",
    subregion: "Central America",
    flag: "🇭🇳",
    latlng: [15, -86.5],
    difficulty: "hard",
  },
  {
    name: "Guatemala",
    code: "GT",
    capital: "Guatemala City",
    region: "Americas",
    subregion: "Central America",
    flag: "🇬🇹",
    latlng: [15.5, -90.25],
    difficulty: "hard",
  },
  {
    name: "El Salvador",
    code: "SV",
    capital: "San Salvador",
    region: "Americas",
    subregion: "Central America",
    flag: "🇸🇻",
    latlng: [13.8333, -88.9167],
    difficulty: "hard",
  },
  {
    name: "Nicaragua",
    code: "NI",
    capital: "Managua",
    region: "Americas",
    subregion: "Central America",
    flag: "🇳🇮",
    latlng: [13, -85],
    difficulty: "hard",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    capital: "Santo Domingo",
    region: "Americas",
    subregion: "Caribbean",
    flag: "🇩🇴",
    latlng: [19, -70.6667],
    difficulty: "hard",
  },
  {
    name: "Haiti",
    code: "HT",
    capital: "Port-au-Prince",
    region: "Americas",
    subregion: "Caribbean",
    flag: "🇭🇹",
    latlng: [19, -72.4167],
    difficulty: "hard",
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    capital: "Port of Spain",
    region: "Americas",
    subregion: "Caribbean",
    flag: "🇹🇹",
    latlng: [11, -61],
    difficulty: "hard",
  },
  {
    name: "Barbados",
    code: "BB",
    capital: "Bridgetown",
    region: "Americas",
    subregion: "Caribbean",
    flag: "🇧🇧",
    latlng: [13.1667, -59.5333],
    difficulty: "hard",
  },
  {
    name: "Bahamas",
    code: "BS",
    capital: "Nassau",
    region: "Americas",
    subregion: "Caribbean",
    flag: "🇧🇸",
    latlng: [24.25, -76],
    difficulty: "hard",
  },
  {
    name: "Fiji",
    code: "FJ",
    capital: "Suva",
    region: "Oceania",
    subregion: "Melanesia",
    flag: "🇫🇯",
    latlng: [-18, 175],
    difficulty: "hard",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    capital: "Port Moresby",
    region: "Oceania",
    subregion: "Melanesia",
    flag: "🇵🇬",
    latlng: [-6, 147],
    difficulty: "hard",
  },
  {
    name: "North Korea",
    code: "KP",
    capital: "Pyongyang",
    region: "Asia",
    subregion: "Eastern Asia",
    flag: "🇰🇵",
    latlng: [40, 127],
    difficulty: "hard",
  },
  {
    name: "Maldives",
    code: "MV",
    capital: "Malé",
    region: "Asia",
    subregion: "Southern Asia",
    flag: "🇲🇻",
    latlng: [3.25, 73],
    difficulty: "hard",
  },
  {
    name: "Albania",
    code: "AL",
    capital: "Tirana",
    region: "Europe",
    subregion: "Southern Europe",
    flag: "🇦🇱",
    latlng: [41, 20],
    difficulty: "hard",
  },
  {
    name: "North Macedonia",
    code: "MK",
    capital: "Skopje",
    region: "Europe",
    subregion: "Southern Europe",
    flag: "🇲🇰",
    latlng: [41.8333, 22],
    difficulty: "hard",
  },
  {
    name: "Montenegro",
    code: "ME",
    capital: "Podgorica",
    region: "Europe",
    subregion: "Southern Europe",
    flag: "🇲🇪",
    latlng: [42.5, 19.3],
    difficulty: "hard",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    capital: "Sarajevo",
    region: "Europe",
    subregion: "Southern Europe",
    flag: "🇧🇦",
    latlng: [44, 18],
    difficulty: "hard",
  },
  {
    name: "Belarus",
    code: "BY",
    capital: "Minsk",
    region: "Europe",
    subregion: "Eastern Europe",
    flag: "🇧🇾",
    latlng: [53, 28],
    difficulty: "hard",
  },
  {
    name: "Moldova",
    code: "MD",
    capital: "Chișinău",
    region: "Europe",
    subregion: "Eastern Europe",
    flag: "🇲🇩",
    latlng: [47, 29],
    difficulty: "hard",
  },
]

// Country outlines SVG paths (simplified for key countries)
export const countryOutlines: Record<string, string> = {
  US: "M0 20 L10 15 L20 18 L30 12 L40 15 L50 10 L55 15 L60 12 L70 18 L75 15 L80 20 L85 25 L80 35 L70 40 L60 38 L50 42 L40 38 L30 42 L20 38 L10 40 L5 35 L0 30 Z",
  GB: "M15 5 L25 0 L35 5 L40 15 L35 25 L30 30 L25 35 L15 30 L10 20 L15 10 Z",
  FR: "M10 5 L30 0 L50 5 L55 20 L50 35 L40 45 L25 40 L10 45 L5 30 L10 15 Z",
  DE: "M15 0 L35 5 L50 0 L55 15 L50 30 L40 40 L25 35 L10 40 L5 25 L10 10 Z",
  IT: "M20 0 L35 5 L45 0 L50 20 L45 40 L35 60 L25 55 L15 65 L10 50 L15 30 L20 15 Z",
  JP: "M10 10 L25 5 L40 15 L45 30 L40 45 L25 50 L15 45 L10 30 Z M50 20 L60 15 L65 25 L55 30 Z",
  BR: "M10 5 L30 0 L50 5 L60 15 L65 35 L60 55 L50 70 L35 75 L20 70 L10 55 L5 35 L10 20 Z",
  AU: "M5 20 L20 10 L40 5 L60 10 L75 20 L80 35 L75 50 L60 55 L40 58 L20 55 L10 45 L5 35 Z",
  CN: "M5 15 L25 5 L50 10 L70 5 L85 15 L90 30 L85 45 L70 55 L50 50 L30 55 L15 45 L5 30 Z",
  IN: "M15 5 L35 0 L50 10 L55 30 L50 50 L35 60 L20 55 L15 45 L10 25 Z",
  RU: "M0 15 L30 5 L60 10 L90 5 L100 15 L95 30 L85 40 L60 35 L40 40 L20 35 L5 30 Z",
  CA: "M0 25 L20 15 L40 10 L60 15 L80 10 L95 20 L90 35 L75 45 L55 40 L40 45 L25 40 L10 45 L5 35 Z",
  MX: "M5 10 L25 5 L40 10 L50 20 L45 35 L35 45 L20 40 L10 30 L5 20 Z",
  AR: "M15 0 L30 5 L35 20 L30 40 L25 60 L20 75 L15 65 L10 45 L5 25 L10 10 Z",
  EG: "M10 5 L40 0 L50 15 L45 35 L30 45 L15 40 L5 25 L10 15 Z",
  ZA: "M10 5 L35 0 L50 10 L55 25 L50 40 L35 45 L20 40 L10 30 L5 15 Z",
  KR: "M10 5 L25 0 L35 10 L30 25 L20 35 L10 25 L5 15 Z",
  ES: "M5 10 L30 5 L50 10 L55 25 L45 35 L30 40 L15 35 L5 25 Z",
  TR: "M0 15 L30 10 L55 15 L60 25 L50 35 L30 30 L10 35 L5 25 Z",
  PL: "M10 5 L40 0 L50 10 L45 25 L35 30 L20 28 L10 20 Z",
  TH: "M15 5 L30 0 L40 10 L45 30 L40 50 L30 55 L20 45 L15 25 Z",
  ID: "M0 15 L15 10 L30 15 L35 20 L50 15 L65 20 L75 15 L80 25 L70 30 L55 28 L40 32 L25 28 L10 30 L5 22 Z",
}

// SVG paths for country shapes (more detailed)
export function getCountryPath(code: string): string {
  return countryOutlines[code] || "M10 10 L40 10 L40 40 L10 40 Z"
}

export function getCountriesByDifficulty(difficulty: "easy" | "medium" | "hard"): Country[] {
  if (difficulty === "easy") {
    return countries.filter((c) => c.difficulty === "easy")
  }
  if (difficulty === "medium") {
    return countries.filter((c) => c.difficulty === "easy" || c.difficulty === "medium")
  }
  return countries
}

export function getRandomCountries(
  count: number,
  exclude?: string,
  difficulty?: "easy" | "medium" | "hard",
): Country[] {
  const pool = difficulty ? getCountriesByDifficulty(difficulty) : countries
  const filtered = exclude ? pool.filter((c) => c.name !== exclude) : pool
  const shuffled = [...filtered].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}

export function getRandomCountry(difficulty?: "easy" | "medium" | "hard"): Country {
  const pool = difficulty ? getCountriesByDifficulty(difficulty) : countries
  return pool[Math.floor(Math.random() * pool.length)]
}

// Daily challenge - generates consistent question for the day
export function getDailyChallenge(): { country: Country; type: "flag" | "capital" | "outline" } {
  const today = new Date()
  const seed = today.getFullYear() * 10000 + (today.getMonth() + 1) * 100 + today.getDate()
  const countryIndex = seed % countries.length
  const types: ("flag" | "capital" | "outline")[] = ["flag", "capital", "outline"]
  const typeIndex = seed % 3

  return {
    country: countries[countryIndex],
    type: types[typeIndex],
  }
}
